language: node_js

node_js:
  - "5"

addons:
  apt:
    packages:
    - npm
    - nodejs-legacy

sudo: true

branches:
  only:
  - master

install:
  - npm cache clean
  - npm install
  - npm config set strict-ssl false
  - sudo npm i npm@latest -g
  - which node
  - which nodejs
  - npm -v
  - sudo npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant

release:
  - exit 0
